name = "ptrk-fm-worker"
type = "javascript"

account_id = ""
workers_dev = true
compatibility_date = "2022-03-11"

kv_namespaces = [ 
  { binding = "ARTICLES", id = "" }
]

[vars]
S3_ACCESS_KEY_ID = ""
S3_SECRET_KEY = ""
LOGIN = ""
PASSWORD = ""
BUCKET_NAME = ""

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
