name = "ptrk-fm-worker"
type = "javascript"

account_id = "32ec5a45e61bb65267a5e522f2d1425d"
workers_dev = true
compatibility_date = "2022-03-11"

# this should be created manually in cloudflare..
# workers -> worker -> settings -> KV namespace bindings
kv_namespaces = [ 
  { binding = "ARTICLES", id = "d28de518cd11446db0829b715df74299" }
]

[vars]
AWS_REGION = "eu-central-1"
BUCKET_NAME = "ptrk"

## AWS KEY ID AND KEY | AWS - ACC - SECURITY Credentials - Access Key
## LOGIN AND PASSWORD for admin panel
# notion - settings and members - integrations - develop your own...

# [secrets]
# AWS_ACCESS_KEY_ID
# AWS_SECRET_KEY
# LOGIN
# PASSWORD
# NOTION_INTEGRATION_TOKEN

[build]
command = "npm ci --production && npm run build"

[build.upload]
format = "service-worker"
