name = "ptrk-fm-worker"
type = "webpack"

account_id = "AccountID"
workers_dev = true
compatibility_date = "2022-03-11"
webpack_config = "webpack.config.js"

[vars]
LOGIN = "YourLogin"
PASSWORD = "YourPassword"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"