name = "ptrk-fm-worker"
type = "javascript"

### Workers -> AccountID
account_id = "" 

workers_dev = true
compatibility_date = "2022-03-11"

### Workers -> KV -> Choose ID from namespaces table or create another namespace
kv_namespaces = [ 
  { binding = "ARTICLES", id = "" } 
]

[vars]
AWS_REGION = "us-east-1"
BUCKET_NAME = "blog-api-dev-image-bucket"

### AWS_ACCESS_KEY_ID & AWS_SECRET_KEY | In AWS - Your profile -> Security credentials -> Access keys
### LOGIN & PASSWORD                   | For admin panel
### NOTION_INTEGRATION_TOKEN           | In Notion Workspace - Settings & Members -> Integrations -> Develop your own integrations -> *Create or choose integration* -> Internal Integration Token
###                                    | Come back to Notion Workspace -> Share -> Invite -> *Choose integration*

# [secrets]
# AWS_ACCESS_KEY_ID
# AWS_SECRET_KEY
# LOGIN
# PASSWORD
# NOTION_INTEGRATION_TOKEN

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
